### ISSUE TITLE
Tagging new release?

### ISSUE THREAD

**Issue by JohnHBrock** [JuliaDatabases/Redis.jl#41]
The most recent tag is over a year old.

**Comment by merl-dev** [comment]
I think a few decisions have to be made regarding the core bindings to Redis, whether libhiredis should be used instead of the pure Julia version.  Another issue is whether some Redis responses need to be converted to `Dict` or other types.  These issues have major performance implications.  In a recent production system we opted for libhiredis and no conversions in order to maximise throughput and with little change to the Redis.jl API.  That system is running smoothly, so I would have to update the repo and make the proposed changes available for review.  Unfortunately I have been preoccupied with other projects lately.  You could take a look at https://github.com/merl-dev/Redis.jl.  The master contains much of what I intended to propose.  Some sentinel testing needs to be added, in addition to code for cluster management.

**Comment by jkaye2012** [comment]
Closing as this should be done shortly following the JuliaDatabases move.
