### ISSUE TITLE
Please rewrite examples with FQ function/method names

### ISSUE THREAD

**Issue by DRVTiny** [JuliaDatabases/Redis.jl#44]
set and get function names exported by Redis package is too common, so the code using this functions without "Redis." prefix is very unclear and vexing.

If you can, please add to examples some short piece of code, which make it obvious how to get ordinary string from Nullable{String}. It will be helpful for totally newbies like me and can lower barrier to entry for Julia newcomers :)

Thank you very much!

**Comment by merl-dev** [comment]
1. you should be using Redis. prefix in this version of Redis.jl.  
2. if `myvariable` is of type `Nullable{String}`, then `myvariable.value` will retrieve the string

There has been quite a bit of discussion surrounding Null values in Julia, and I am not sure where it will all settle.  This debate has implications for the performance of a Julia Redis client, since there are a number of Redis commands that return a mix of types which may include null (nil) values. See for example [Nullable vs Union](https://discourse.julialang.org/t/nullable-vs-union/589), and [Representing Nullable Values](https://discourse.julialang.org/t/representing-nullable-values/4729).  I have been waiting patiently for more progress before making any new pull requests for a type stable version of the Redis client.
