### ISSUE TITLE
TagBot

### ISSUE THREAD

**Issue by vitornesello** [JuliaDatabases/Redis.jl#94]
Hi @jkaye2012

It looks like the tag bot is not working for this repo due to inactivity. Is there an easy way to put it back to work? I think that the latest release (2.0) did not go to the registry

**Comment by vitornesello** [comment]
Maybe I can help to maintain this project if you need a hand. I would need some rights though

**Comment by jkaye2012** [comment]
Hi Vitor, I'd be very happy to have some help on maintenance here from someone who's more actively involved in the ecosystem these days. Unfortunately it seems like this type of access has to be handled at the JuliaDatabases level, as I don't seem to have access to modify settings on this repository since it's been moved into the organization. I'm sure that this is something we can get worked out for you though.

**Comment by tanmaykm** [comment]
TagBot is now working fine on this repo after updates done in https://github.com/JuliaDatabases/Redis.jl/pull/96. The recent registration of [v2.1.0](https://github.com/JuliaDatabases/Redis.jl/releases/tag/v2.1.0) was tagged successfully by TagBot.

I think this issue can now be closed.
